### PR TITLE
PSE-2021

### PR DESCRIPTION
**Pull request by waldleben**
To review branch, run server on pse-2021 branch and change baseUrl in catalog.service.ts to http://0.0.0.0:3000/.

Issue:
- 3 tests in main.component.spec.ts are disabled, because of failure. Those tests are also failing on the current master branch. We couldn't figure out why.

The new Klv1 detailview is not implemented.

### CODE REVIEW

**Comment by tschimbr** [comment]
@waldleben As far as I can say the code looks good to me. Two small issues:
1. Can we add breadcrumbs in the detail view so we can navigate back to the whole KLV1 or to a chapter. Same as in the other catalogs?
2. We should add a small margin (1-2px) between navigation elements (catalog pickers) when we have two lines displayed.

**Comment by waldleben** [comment]
@tschimbr Thank you for the quick review. Regarding the issues:

1. Yes, we can add the breadcrumb feature. For that the API Response needs to be updated, but it shouldn't be to much work. 
2. I will add the margin for the mobile view.

**Comment by waldleben** [comment]
@tschimbr If a requirement/ valid_from has no content, should "Keine" be displayed, the text "Voraussetzung:" without content or no text at all?

Screenshot from 2021-04-29 13-46-59

**Comment by tschimbr** [comment]
@waldleben I think the solution in the screenshot with "Keine" is the most clear.

**Pull request merged**
